### ISSUE TITLE
Simple non-list Clojure expression always evaluates as nil

### ISSUE THREAD

**Issue by vmarcinko** [viebel/klipse#114]
Unlike other Clojurescript-bootstraped REPLs I have tried, KLIPSE doesn't evaluate simple non-list expressions to themselves...

Example: "hello" should evaluate to itself, but instead the result is nil

**Comment by viebel** [comment]
This is because, in KLIPSE, we evaluate several expressions while in console-based REPL only one expression is evaluated. You can configure the mode with the `eval-context` url parameter as explained [here](https://github.com/viebel/klipse/blob/92fe42c615d1da0db8dd8ec99c4e136ddff5f3d7/repl.md#url-parameters).

**Comment by vmarcinko** [comment]
Ah, didn't notice that.
