### ISSUE TITLE
No error message when using undeclared variable

### ISSUE THREAD

**Issue by rinama** [viebel/klipse#26]
When evaluating `(map inc 1234)`  I get the message `1234 is not ISeqable`.
But when evaluating `(str hello world)` no error message is displayed in the cljs panel, Instead 
`;; Press Ctrl-Enter or wait for 3 sec to eval in clojure...` is written.

**Comment by viebel** [comment]
The reason is that it's not an error. 
Look at the transpiled js code here: [KLIPSE](http://app.klipse.tech/?cljs_in=(str%20%22start%20%22%20hello%20world%20%22%20end%22))

`hello` is translated to `cljs.user.hello` which is undefined

There is a warning but we don't display warnings in KLIPSE (for the moment).
