### ISSUE TITLE
eval/print primitives

### ISSUE THREAD

**Issue by shaunlebron** [viebel/klipse#28]
Try the following values in klipse:

- `:foo`
- `"foo"`
- `123`

Neither of them seem to print a result.

**Comment by Jell** [comment]
perhaps related:

```
(def x 3)
x
```
returns
```
#'cljs.user/x
```
instead of
```
3
```

**Comment by viebel** [comment]
@shaunlebron @Jell 

I have added recently support for primitive evaluation: In order to evaluates properly primitive one has to add a `eval-context=expr` in the url, like this:
http://app.klipse.tech/?eval-context=expr

For instance, this one works properly:
http://app.klipse.tech/?cljs_in=%3Afoo&eval-context=expr



![image](https://cloud.githubusercontent.com/assets/955710/17307102/150cd708-583c-11e6-802e-518d2244be08.png)

Here is the [full list of url parameters](http://blog.klipse.tech/clojure/2016/03/27/klipse-manual.html)
