### ISSUE TITLE
ublock (adblocker) stop loading of klipse 

### ISSUE THREAD

**Issue by JulienRouse** [viebel/klipse#311]
Hi,

I seem to have a problem with my klipse code not loading or not running when my adblocker is on.

It is not an issue when viewing this [page](http://blog.klipse.tech/clojure/2016/06/07/klipse-plugin-tuto.html)
but it is on my personnal [page](https://www.julienrouse.com/template/articles/en/2018-05-27_Start_of_a_new_ClojureScript_Project.html)).

When I view my page with ublock on, I get the error "#error {:message "No such namespace: reagent.core, could not locate reagent/core.cljs, reagent/core.cljc, or Closure namespace \"reagent.core\"", :data {:tag :cljs/analysis-error}}'.

When I view the page with ublock off, it display as it should. 

My klispe settings are 

 ```
<script>
    window.klipse_settings = {
         selector: '.language-klipse',// css selector for the html elements you want to klipsify
         selector_reagent: '.language-reagent', // selector for reagent snippets
		codemirror_options_in: {
			indentUnit: 8,
			lineWrapping: true,
			lineNumbers: true,
			autoCloseBrackets: true
		},
		codemirror_options_out: {
			lineWrapping: true,
			lineNumbers: true
		}
	}
</script>
```

Is there anything I should add/change in the settings?

Another information, my blog page is hosted by Github Page, could it be an issue? 

Thanks, if you need any more clarification or information I'll be happy to send them

Julien 

Edit: The same behavior is happening in the section "Using external libraries" of the [gitbook about klipse](https://book.klipse.tech/interactive_clojure[script]_code_snippets.html)

**Comment by OvermindDL1** [comment]
Sounds like ublock is being a bit too picky, you should probably submit an ignore request there (linking back to this issue).

_/me prefers uMatrix for the fine control, though it takes more effort at the start, it is well worth it_

**Comment by JulienRouse** [comment]
I'm sorry I'm gonna ask because I'm not sure I did clearly understood what you're saying. You suggest I should contact uBlock to let them know they have a false positive?

Thanks  for your answer, I'm gonna look what uMatrix looks like.

**Comment by OvermindDL1** [comment]
@JulienRouse in general yes, they need to clear their false positive, it's not something klipse can really do without breaking backwards compatibility.

**Comment by viebel** [comment]
@JulienRouse I took a look at your [article](https://www.julienrouse.com/template/articles/en/2018-05-27_Start_of_a_new_ClojureScript_Project.html) that demonstrates Clojurescript and reagent inside it. 
It looks really nice and this is really awesome for the readers to be able to interact with your code and see immediately the effect of their code changes.


In order to make it even more awesome for the readers, I would recommend to split your code into several code snippets and interleave pieces of text and code to describe your code (think about Literate programming).  See for example this [article](http://blog.klipse.tech/omnibus/2017/04/23/omnibus-1-wallpaper.html).

Enjoy!

**Comment by JulienRouse** [comment]
@viebel  Thanks for your kind words. It's actually work in progress to split the acticle more into each steps of the process. 
 
The article you linked as an example is great thanks, great source of inspiration :)
