### ISSUE TITLE
Uncaught TypeError: Cannot set property 'JA' of undefined

### ISSUE THREAD

**Issue by polytypic** [viebel/klipse#329]
Hmm... Something seems to have changed in a recent release of Klipse as now my uses of Klipse, such as [this page](https://polytypic.github.io/fastener/index.html), produce the following error (in the console:

```
Uncaught TypeError: Cannot set property 'JA' of undefined
    at klipse_plugin.min.js:39550
    at klipse_plugin.min.js:46990
```

Is this a bug in Klipse or has something changed in the way Klipse is to be embedded into a page?

I also couldn't find a changelog or history file for Klipse.  Is there such a document?

**Comment by viebel** [comment]
This is a bug in Klipse that has been cause by the latest deployment.
The bug was caused by this commit https://github.com/viebel/klipse/commit/4d19579f9416b3217faf2aabdc6dd560888edccf

I found the root cause. 
I am expecting to deploy a fix later today.

Sorry for the inconvenience (It also broke my personal blog)

**Comment by viebel** [comment]
Hi @polytypic 
The issue has been fixed and I just deployed it.
It might take some time until the new version appears due to browser cache
Please check in the browser console that you see Klipse version 7.6.8 and confirm that the bug is indeed fixed.
